backend:
  name: github
  repo: jinjcovsky/woistjan
  branch: main
  base_url: https://woistjan-proxy.jkienast-at.workers.dev

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Latitude", name: "lat", widget: "number", value_type: "float", required: false, default: 47.2692}
      - {label: "Longitude", name: "lon", widget: "number", value_type: "float", required: false, default: 11.4041}
      - {label: "Body", name: "body", widget: "markdown"}
